// CREATE TABLE IF NOT EXISTS products(
// id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
// name VARCHAR(255) NOT NULL,
// price DECIMAL(10, 2) NOT NULL,
// stock_quantity INT(11) NOT NULL,
// created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
// updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
// deleted_at TIMESTAMP NULL,
// supplier_id INT,
// FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE ON UPDATE CASCADE
// );