


// CREATE TABLE IF NOT EXISTS sales(
//  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
//  date DATE,
//  quantity_sold INT(11) NOT NULL,
//  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
// updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
// deleted_at TIMESTAMP NULL,
// product_id INT,
// FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE ON UPDATE CASCADE



// );
