// CREATE TABLE IF NOT EXISTS suppliers (
// id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
// name VARCHAR(255) NOT NULL UNIQUE,
// contact_number VARCHAR(255),
// created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
// updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
// deleted_at TIMESTAMP NULL
// );
